name: Test and Build app

# Trigger to run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

jobs:
  # Test syntax by checking formatting
  lint:
    name: Lint files
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
   
  # Test Functionality
  test:
    name: Run tests
    runs-on: 'ubuntu-latest'
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - run: go test -v -cover
  
  # Test build stability for Linux and Windows
  build:
    name: Build binary
    runs-on: 'ubuntu-latest'
    needs: test
    strategy:
      matrix:
        goosarch:
          #- 'aix/ppc64'
          # - 'android/386'
          #- 'android/amd64'
          # - 'android/arm'
          #- 'android/arm64'
          #- 'darwin/amd64'
          #- 'darwin/arm64'
          #- 'dragonfly/amd64'
          #- 'freebsd/386'
          #- 'freebsd/amd64'
          #- 'freebsd/arm'
          #- 'freebsd/arm64'
          #- 'illumos/amd64'
          # - 'ios/amd64'
          # - 'ios/arm64'
          #- 'js/wasm'
          #- 'linux/386'
          - 'linux/amd64'
          #- 'linux/arm'
          #- 'linux/arm64'
          #- 'linux/mips'
          #- 'linux/mips64'
          #- 'linux/mips64le'
          #- 'linux/mipsle'
          #- 'linux/ppc64'
          #- 'linux/ppc64le'
          #- 'linux/riscv64'
          #- 'linux/s390x'
          #- 'netbsd/386'
          #- 'netbsd/amd64'
          # 'netbsd/arm'
          #- 'netbsd/arm64'
          #- 'openbsd/386'
          #- 'openbsd/amd64'
          #- 'openbsd/arm'
          #- 'openbsd/arm64'
          #- 'openbsd/mips64'
          #- 'plan9/386'
          #- 'plan9/amd64'
          #- 'plan9/arm'
          #- 'solaris/amd64'
          #- 'windows/386'
          - 'windows/amd64'
          #- 'windows/arm'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Get OS and arch info
        run: |
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=${{github.repository}}-$GOOS-$GOARCH-${{steps.getversion.outputs.version}}
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV
      - name: Build
        run: |
          go build -o "$BINARY_NAME" -v
          
      # Create Release
      - name: Add file to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.getversion.outputs.version}}
          release_name: ${{steps.getversion.outputs.version}}
          files: ${{env.BINARY_NAME}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  # Create Release
  release:
    name: Create Release
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read VERSION file
        id: version
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Release Notes
        run:
          echo "${{github.event.head_commit.message}}" >> ".github/RELEASE-TEMPLATE.md"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version.outputs.version}}
          release_name: ${{steps.version.outputs.version}}
          body_path: ".github/RELEASE-TEMPLATE.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
